"""Custom tool: text_summarizer

Generated by tools/scaffold_tool.py.
"""

from __future__ import annotations

from typing import Any, Optional
from coworker.tools.base import coworker_tool, tool_success, tool_error


@coworker_tool(
    name="text_summarizer",
    category="custom",
    requires_approval=False,
    description="Tóm tắt văn bản và đếm số từ",
)
def text_summarizer(query: str, count: Optional[int] = 5) -> dict[str, Any]:
    """Tóm tắt văn bản và đếm số từ

    Args:
        query: Chuỗi truy vấn hoặc tham số đầu vào chính.
        count: Số lượng kết quả mong muốn (mặc định: 5).
    """
    if not query or not query.strip():
        return tool_error("Tham số 'query' không được để trống.")

    try:
        # TODO: Cài đặt logic thực thi cụ thể tại đây
        results = [f"Result {i+1} for '{query.strip()}'" for i in range(count or 5)]
        return tool_success(data={"query": query, "count": len(results), "items": results})
    except Exception as exc:
        return tool_error(f"Lỗi khi thực thi text_summarizer: {exc}")
