#!/usr/bin/env python3
"""Tool Scaffolding CLI for AI-COWORK.

Quickly and reliably generate new tools (either standalone in `custom_tools/` or
integrated into `connect-ai/coworker/tools/`) along with standardized boilerplate,
type hints, docstrings, and unit test suites.

Usage:
    # 1. Tạo custom tool nhanh (khuyên dùng):
    python tools/scaffold_tool.py --name weather_lookup --desc "Tra cứu thời tiết theo thành phố"

    # 2. Tạo core tool tích hợp vào connect-ai:
    python tools/scaffold_tool.py --name my_core_tool --type core --category dev_shell --desc "Mô tả tool"
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _validate_name(name: str) -> str:
    cleaned = name.strip().lower()
    if not re.match(r"^[a-z][a-z0-9_]*$", cleaned):
        raise ValueError(
            f"Invalid tool name '{name}'. Must be snake_case (e.g. 'calc_sum', 'weather_lookup')."
        )
    return cleaned


def generate_custom_tool(name: str, desc: str, category: str, requires_approval: bool) -> Path:
    target_dir = ROOT / "custom_tools"
    target_dir.mkdir(parents=True, exist_ok=True)
    target_file = target_dir / f"{name}.py"

    if target_file.exists():
        print(f"[warn] File {target_file} already exists. Skipping overwrite.")
        return target_file

    code = f'''"""Custom tool: {name}

Generated by tools/scaffold_tool.py.
"""

from __future__ import annotations

from typing import Any, Optional
from coworker.tools.base import coworker_tool, tool_success, tool_error


@coworker_tool(
    name="{name}",
    category="{category}",
    requires_approval={requires_approval},
    description="{desc}",
)
def {name}(query: str, count: Optional[int] = 5) -> dict[str, Any]:
    """{desc}

    Args:
        query: Chuỗi truy vấn hoặc tham số đầu vào chính.
        count: Số lượng kết quả mong muốn (mặc định: 5).
    """
    if not query or not query.strip():
        return tool_error("Tham số 'query' không được để trống.")

    try:
        # TODO: Cài đặt logic thực thi cụ thể tại đây
        results = [f"Result {{i+1}} for '{{query.strip()}}'" for i in range(count or 5)]
        return tool_success(data={{"query": query, "count": len(results), "items": results}})
    except Exception as exc:
        return tool_error(f"Lỗi khi thực thi {name}: {{exc}}")
'''
    target_file.write_text(code, encoding="utf-8")
    print(f"[create] Custom tool created: {target_file}")
    return target_file


def generate_core_tool(name: str, desc: str, category: str, requires_approval: bool) -> Path:
    tools_dir = ROOT / "connect-ai" / "coworker" / "tools"
    tools_dir.mkdir(parents=True, exist_ok=True)
    target_file = tools_dir / f"{name}.py"

    if target_file.exists():
        print(f"[warn] File {target_file} already exists. Skipping overwrite.")
        return target_file

    code = f'''"""Built-in tool: {name}

Generated by tools/scaffold_tool.py.
"""

from __future__ import annotations

from typing import Any, Optional
from .base import coworker_tool, tool_success, tool_error


@coworker_tool(
    name="{name}",
    category="{category}",
    requires_approval={requires_approval},
    description="{desc}",
)
def {name}(query: str, limit: Optional[int] = 10) -> dict[str, Any]:
    """{desc}

    Args:
        query: Tham số truy vấn chính.
        limit: Giới hạn số lượng (mặc định: 10).
    """
    if not query.strip():
        return tool_error("Query không được để trống.")

    # Implementation logic
    return tool_success(data={{"query": query, "limit": limit}})
'''
    target_file.write_text(code, encoding="utf-8")
    print(f"[create] Core tool created: {target_file}")
    return target_file


def generate_test(name: str, is_core: bool = False) -> Path:
    test_dir = ROOT / "connect-ai" / "tests"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_file = test_dir / f"test_tool_{name}.py"

    if test_file.exists():
        print(f"[warn] Test file {test_file} already exists. Skipping.")
        return test_file

    import_stmt = (
        f"from coworker.tools.{name} import {name}"
        if is_core
        else f"from custom_tools.{name} import {name}"
    )

    code = f'''"""Unit test for tool: {name}"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import pytest
{import_stmt}


def test_{name}_success():
    result = {name}(query="test query", count=3)
    assert result["ok"] is True
    assert "data" in result


def test_{name}_empty_query():
    result = {name}(query="   ")
    assert result["ok"] is False
    assert "error" in result
'''
    test_file.write_text(code, encoding="utf-8")
    print(f"[create] Unit test created: {test_file}")
    return test_file


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="AI-COWORK Tool Scaffolder")
    parser.add_argument("--name", required=True, help="Tên tool (snake_case, ví dụ: my_calculator)")
    parser.add_argument("--desc", default="Mô tả công cụ mới", help="Mô tả chức năng của tool")
    parser.add_argument(
        "--type",
        choices=["custom", "core"],
        default="custom",
        help="Loại tool: 'custom' (thư mục custom_tools/) hoặc 'core' (connect-ai/coworker/tools/)",
    )
    parser.add_argument(
        "--category",
        default="custom",
        help="Category: core, browser, crawl, dev_shell, connectors, automation, custom",
    )
    parser.add_argument(
        "--requires-approval",
        action="store_true",
        help="Tool yêu cầu người dùng phê duyệt trước khi thực thi",
    )
    parser.add_argument(
        "--no-test",
        action="store_true",
        help="Không tự động tạo file test",
    )

    args = parser.parse_args()

    try:
        tool_name = _validate_name(args.name)
    except ValueError as e:
        print(f"[error] {e}", file=sys.stderr)
        return 1

    if args.type == "custom":
        generate_custom_tool(tool_name, args.desc, args.category, args.requires_approval)
    else:
        generate_core_tool(tool_name, args.desc, args.category, args.requires_approval)

    if not args.no_test:
        generate_test(tool_name, is_core=(args.type == "core"))

    print("\n[success] Tool created successfully! You can customize logic and run tests now.")
    if not args.no_test:
        print(f"[test] Run: pytest connect-ai/tests/test_tool_{tool_name}.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
